package com.dprince.entities.enums;

public enum AppFeature {
    LOGIN_SMS,
    SMS_SENDING,
    WHATSAPP,
    CUSTOM_RECEIPT,
    CUSTOM_ORGANIZATION_LOGO,
    COMMUNICATION,
    ADDRESS_PRINTING_MULTI_PRINTER_OPTION,
    IMPORT_EXISTING_PARTNER,
    CERTIFICATE,
    TWO_FACTOR_AUTHENTICATION,

    AI_FEATURES,
    CUSTOM_REPLY_EMAIL,
    WHITE_LABEL,
    PARTNER_LOGIN,
    MULTI_CREDIT_ACCOUNT,
    ACCOUNTS_INTEGRATION,
    AUTO_REPORT,


    MEMBER_GROUPS
}
