package com.dprince.entities.enums;

public enum UserType {
    ORGANIZATION_PARTNER,
    ORGANIZATION_ADMINISTRATOR,
    ORGANIZATION_ASSISTANT_ADMINISTRATOR,
    ORGANIZATION_DATA_ENTRY_OPERATOR,

    CHURCH_MEMBER,
    CHURCH_ADMINISTRATOR,
    CHURCH_ASSISTANT_ADMINISTRATOR,
    CHURCH_DATA_ENTRY_OPERATOR,

    CHURCH_BRANCH_ADMINISTRATOR,
    CHURCH_BRANCH_ASSISTANT_ADMINISTRATOR,

    SUPER_ASSISTANT_ADMINISTRATOR,
    SUPER_ADMINISTRATOR,


    APPLICATION
}
