export const DEFAULT_MEMBER = {
    "titleId": 5169,
    "firstName": "flori",
    "lastName": "levi",
    "gender": "MALE",
    "dob": "2001-08-19T18:30:00.000Z",
    "addressLine1": "9/61 Railway Station Road Arasu Colony",
    "addressLine2": "EdamalaiPattiPudur",
    "addressLine3": "ARADU COLONY",
    "pincode": 620012,
    "district": "Tiruchirappalli",
    "state": "TAMIL NADU",
    "country": "IN",
    "phone": 7418505117,
    "phoneCode": 91,
    "alternatePhoneCode": 91,
    "landlinePhoneCode": 91,
    "whatsappNumber": 7418505117,
    "whatsappNumberCode": 91,
    "status": "ACTIVE",
    "email": "22pcs944@mail.sjctni.edu",
    "subscription": "ANNUAL",
    "categoriesIds": [
        111,
        112,
        121
    ],
    "language": "ENGLISH",
    "creationDate": "2025-02-04T18:30:00.000Z",
    "newPinCode": false,
    "familyHead": false,
    "whatsapp": true,
    "clientTimezone": "Asia/Calcutta"
}